[mongodb]
uri = "mongodb+srv://abhishelke2971:Abhi297127@abhi1792.942ohkd.mongodb.net/attendance_db?retryWrites=true&w=majority"
database = "attendance_db"

[app]
title = "Employee Attendance Management System"
debug = false

session_timeout = 3600  

[admin]
default_username = "admin"
default_password = "admin123"  

[security]
password_min_length = 6
session_secret = "y1234567890"  
jwt_secret = "0987654321"      

[email]

[storage]
max_image_size = 5242880  # 5MB in bytes
allowed_image_types = ["jpg", "jpeg", "png", "gif"]
images_per_day_limit = 2